### ISSUE TITLE
The pretrained model and the utils.nms function 

### ISSUE THREAD

**Issue by bestzsq** [duanzhiihao/RAPiD#10]
Hello, I am a newcomer in this field，I met several questions when using this code,hoping someone can help me,Thanks a lot in advance!!!
1. how can i get the pretrained model **dark53_imgnet.pth**, i can only find the weights darknet53.conv.74 which can not be used there?
2. when i try to run train.py, it cost me a lot of time,maybe two hours in evaluation(row 227 in train.py),specificlly,it is the utils.nms function,where the dts size is 1000(most time, conf_thres=0.005 may account for that),I don't know if it is my own problem(I didn't load the pretrained model)? or maybe as the training progresses, the time spent on nms function can become smaller.
![image](https://user-images.githubusercontent.com/22475218/95992585-adc5c200-0e60-11eb-9a1c-ff2e074ab24a.png)

Hoping to get your reply，Thanks!

**Comment by duanzhiihao** [comment]
Hi, thank you for your interest in our project.

> how can i get the pretrained model dark53_imgnet.pth, i can only find the weights darknet53.conv.74 which can not be used there?

Sorry that I didn't upload it! You can find it in the **Training on COCO** section in the README now. I will try to give more instructions on training in the README.

> when i try to run train.py, it cost me a lot of time,maybe two hours in evaluation(row 227 in train.py),specificlly,it is the utils.nms function,where the dts size is 1000(most time, conf_thres=0.005 may account for that)

You are right, the evaluation is slow since the rotated bbox NMS is slow. This is especially a problem when there are a lot of garbage predictions in the starting phase of the training. Typically, I skip the evaluation in the first 2k iterations to avoid this problem.

> maybe as the training progresses, the time spent on nms function can become smaller.

Yes, typically it costs around 10-15min to evaluate on 2000 images as the training progresses.

**Comment by bestzsq** [comment]
Thank you for your reply which is helpful to me!!!
