### ISSUE TITLE
Is it necessary that adjust the range of angle of ground truth when 'angran' changes?

### ISSUE THREAD

**Issue by kakusikun** [duanzhiihao/RAPiD#14]
here force the range of angle of ground truth to be -90 ~ 90
https://github.com/duanzhiihao/RAPiD/blob/master/datasets.py#L93

but here is to predict angle in range of -180 ~ 180 ( I guess what the '360' means )
https://github.com/duanzhiihao/RAPiD/blob/master/models/rapid.py#L302 
and here directly use the angle of ground truth
https://github.com/duanzhiihao/RAPiD/blob/master/models/rapid.py#L306

does the angle need to be normalized to -90 ~ 90, i.e., 180 -> 90, 90 -> 45 ? 
or the range of angle of ground truth is changed to be -180 ~ 180 ?

if I missed something, plz let me know.

**Comment by duanzhiihao** [comment]
Yes, the predicted angle is in -180~180 degrees, and the ground truth is -90~90 degrees. The loss is directly calculated between them without normalizing any one of them.

We intentionally made prediction range > GT range. The reason is described in [our paper](https://arxiv.org/pdf/2005.11623.pdf), Figure 4. In short, we expand the prediction range in order to avoid boundary problems.

**Comment by kakusikun** [comment]
thanks for quick reply

but if the predicted angle is 180, what does it mean? 90?

if i do need -45 and 135 to be different, should i change the range of angle of ground truth ?

**Comment by duanzhiihao** [comment]
> but if the predicted angle is 180, what does it mean? 90?

It means 180 degrees, and in our case, 180 degrees is equivalent to 0 degree, because if you rotate a bounding box by 180 degrees, it remains unchanged.

> if i do need -45 and 135 to be different, should i change the range of angle of ground truth ?

Yes. If that's the case, I guess your prediction is not periodic. You can change the range and use a non-periodic loss. For example, Binary Cross Entropy is a typical choice.

**Comment by kakusikun** [comment]
i just figure it out, this work is for periodic case and i should start work at loss, thanks a lot.
