### ISSUE TITLE
Question Regarding AP score

### ISSUE THREAD

**Issue by GivralNguyen** [duanzhiihao/RAPiD#21]
In your paper , i can see that you achieve , 0.919 Precision and 0.951 Recall with confidence 0.3 . However, you achieve AP50 of 96.7. How is this possible when AP is the area under the precision-recall curve ?  .  Let's assume that for all value of confidence > 0.3, you achieve precision = 1. And for all value of confidence <= 0.3, you achieve precision = 0.919. Then your AP will only be 0.919*3 + 0.1*0.7  = 97.3, only slightly higher than the published 96.7 AP in your paper. However, with huge drop-off in precision when confidence <0.3, i have problems understanding the published AP.
Please correct me if i'm wrong

**Comment by duanzhiihao** [comment]
I'm not sure I understand your question, so let me restate how do I compute AP (I'm following the COCO convention).

Given that we achieve 0.919 Precision and 0.951 Recall when conf=0.3, our AP will be >= 0.919*0.951=0.873. Together with additional area when conf < 0.3 (upper left red part) and conf > 0.3 (bottom right red part), the final AP is 96.7.

Note that, the P-R curve is not continuous since in the COCO convention, they sample 101 Recall values and use the averaged Precision corresponding to these 101 Recalls to approximate the area under the P-R curve.

![image](https://user-images.githubusercontent.com/24869582/118001425-4c73bc00-b379-11eb-9403-cccf589dfdff.png)

**Comment by GivralNguyen** [comment]
I see. My bad for not reading clearly about COCO AP convention. Thanks for your detailed answer

**Comment by duanzhiihao** [comment]
No problem, I’m glad that it’s clear now. thank you for your interest!
