### ISSUE TITLE
valJan Dataset?

### ISSUE THREAD

**Issue by nemtiax** [duanzhiihao/RAPiD#9]
train.py contains a reference to a validation dataset called 'valJan'.  I assume it's from your group since the path is "COSSY/valJan".  Is this a separate dataset, or just some validation data taken from HABBOF/CEPDOF/etc.?

```
        train_img_dir = '../../../COCO/train2017'
        train_json = '../../../COCO/annotations/instances_train2017.json'
        val_img_dir = '../../../COSSY/valJan/'
        val_json = '../../../COSSY/annotations/valJan.json'
```

**Comment by duanzhiihao** [comment]
It's a subset of the MW-R dataset. I just randomly selected some images from the [MW-R dataset](http://vip.bu.edu/projects/vsns/cossy/datasets/mw-r/) and named it 'valJan validation set' since I did it in January 2020.

You can do the same thing as me, or you can use any validation set you like. For example, you could choose one of the videos from the HABBOF/CEPDOF as your validation set.

**Comment by nemtiax** [comment]
Makes sense!  I just wanted to make sure it wasn't something critical I was missing.

Thanks for the reply!
